### ISSUE TITLE
千年女王 剧场版聲音畫面不同步

### ISSUE THREAD

**Issue by fox0731** [xiaohaozhi/LFBW-SUBS#2]
您好
千年女王 剧场版發現聲音有比較快,
特寫人物講話時很明顯,聲音先出來,嘴把才動
請問能否修復呢!!? 

另外想順便問是否能發一個純中文的字幕不要中日文的

感謝!!!!!

**Comment by xiaohaozhi** [comment]
尝试修了几次还是有点怪，目前先放弃，可能是TV录制的时候就有的问题，只能等后续有新源再换了。去日文可以用srtedit这个软件。

**Comment by fox0731** [comment]
沒想到6月的問題竟然回復了感動!!
雖然暫時沒解決還是感謝!!!
